# VirtualHost for appli.l2eni.mg
<VirtualHost *:80>
    ServerName appli.l2eni.mg
    Redirect permanent / https://appli.l2eni.mg/
</VirtualHost>

<VirtualHost *:443>
    ServerName appli.l2eni.mg
    DocumentRoot /var/www/appli
    SSLEngine on
    SSLCertificateFile /etc/ssl/l2eni/server.crt
    SSLCertificateKeyFile /etc/ssl/l2eni/server.key

    <Directory /var/www/appli>
        Options +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains"
    Header always set X-Content-Type-Options "nosniff"
    Header always set X-Frame-Options "SAMEORIGIN"

    ErrorLog  ${APACHE_LOG_DIR}/appli-error.log
    CustomLog ${APACHE_LOG_DIR}/appli-access.log combined
</VirtualHost>
