global:
  smtp_smarthost: mail.l2eni.mg:25
  smtp_from: alertmanager@l2eni.mg
  smtp_require_tls: false
route:
  receiver: local-mail
  group_by: [alertname, instance]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
receivers:
  - name: local-mail
    email_configs:
      - to: admin@l2eni.mg
        send_resolved: true
