groups:
  - name: mail-services
    rules:
      - alert: ServiceDown
        expr: node_systemd_unit_state{state="active",name=~"(postfix|dovecot|apache2|slapd|named).service"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Service {{ .name }} is DOWN
      - alert: HighCPU
        expr: 100 - (avg by(instance)(rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: CPU eleve sur {{ .instance }}
      - alert: HighMemory
        expr: (1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Memoire elevee sur {{ .instance }}
